[package]
name = "yt-tur-2"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "yt_tur_2_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-shell = "2.0"
tokio = { version = "1.0", features = ["full"] }
axum = "0.8.4"
reqwest = { version = "0.12", features = ["stream"] }
portpicker = "0.1.1"
once_cell = "1.19"
futures = "0.3"
http = "1.3.1"
urlencoding = "2.1"
url = "2.5.4"

